<div class="container">

  <div class="col-xs-11 form-tabs">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active" id="natural_person" ><a href="#pessoa-fisica" aria-controls="natural_person" role="tab" data-toggle="tab">Pessoa Física</a></li>
      <li role="presentation" id="legal_person" ><a href="#pessoa-juridica" aria-controls="legal_person" role="tab" data-toggle="tab">Pessoa Jurídica</a></li>
    </ul>
  </div>

  <div class="col-xs-11 form-container">

    <form role="form" action="<?= ViewHelpers::urlFor($this->action) ?>" method="POST">

      <input type="hidden" name="client[type]" id="client_type" value="0"/>

      <div class="form-group col-xs-12">

        <div class="form-group col-md-3 <?= $this->client->getErrors('doc') ? 'has-error' : '' ?>">
          <label class="control-label" for="doc" id="label_doc" >CPF:*</label>
          <input type="text" class="form-control" name="client[doc]" value="<?= $this->client->getDoc() ?>"
                 id="doc" placeholder="CPF">
          <p class="help-block"><?= $this->client->getErrors('doc') ?></p>
        </div>

        <div class="form-group col-md-4 <?= $this->client->getErrors('name') ? 'has-error' : '' ?>">
          <label class="control-label" for="name" id="label_name">Nome:*</label>
          <input type="text" class="form-control" name="client[name]" value="<?= $this->client->getName() ?>"
                 id="name" placeholder="Nome" />
          <p class="help-block"><?= $this->client->getErrors('name') ?></p>
        </div>

        <div class="form-group col-md-4 <?= $this->client->getErrors('more_names') ? 'has-error' : '' ?>">
          <label class="control-label" for="more_names" id="label_more_names">Sobrenome:*</label>
          <input type="text" class="form-control" name="client[more_names]" value="<?= $this->client->getMoreNames() ?>"
                 id="more_names" placeholder="Sobrenome">
          <p class="help-block"><?= $this->client->getErrors('more_names') ?></p>
        </div>

      </div>



      <div class="form-group col-xs-12">



        <div class="form-group col-md-2 <?= $this->client->getErrors('zip_code') ? 'has-error' : '' ?>">
          <label class="control-label" for="zip_code">CEP:*</label>
          <input type="text" class="form-control" name="client[zip_code]" value="<?= $this->client->getStreet() ?>"
                 id="zip_code" placeholder="CEP">
          <p class="help-block"><?= $this->client->getErrors('zip_code') ?></p>
        </div>

        <div class="form-group col-md-7 <?= $this->client->getErrors('street') ? 'has-error' : '' ?>">
          <label class="control-label" for="street">Rua:*</label>
          <input type="text" class="form-control" name="client[street]" value="<?= $this->client->getStreet() ?>"
                 id="street" placeholder="Rua">
          <p class="help-block"><?= $this->client->getErrors('street') ?></p>
        </div>

        <div class="form-group col-md-2 <?= $this->client->getErrors('num') ? 'has-error' : '' ?>">
          <label class="control-label" for="num">Número:*</label>
          <input type="text" class="form-control" name="client[num]" value="<?= $this->client->getStreet() ?>"
                 id="num" placeholder="nº">
          <p class="help-block"><?= $this->client->getErrors('num') ?></p>
        </div>

        <div class="form-group col-md-4 <?= $this->client->getErrors('city_id') ? 'has-error' : '' ?>">
          <label class="control-label" for="city">Cidade:*</label>
          <input type="hidden" id="city_id" name="client[city_id]" />
          <input type="text" class="form-control" data-url="<?= ViewHelpers::urlFor('/cidades/auto_complete_cities_search') ?>" value="<?= $this->client->getName() ?>"
                 id="autocomplete_cities" placeholder="Cidade">
          <p class="help-block"><?= $this->client->getErrors('city_id') ?></p>
        </div>

        <div class="form-group col-md-3 <?= $this->client->getErrors('state') ? 'has-error' : '' ?>">
          <label class="control-label" for="client_name">Estado:*</label>
          <input type="hidden" id="state_id" />
          <input type="text" class="form-control" value="<?= $this->client->getName() ?>"
                 id="state_name" placeholder="Estado">
          <p class="help-block"><?= $this->client->getErrors('state') ?></p>
        </div>

        <div class="form-group col-md-2  <?= $this->client->getErrors('country') ? 'has-error' : '' ?>">
          <label class="control-label" for="country">País:*</label>
          <input type="hidden" id="country_id" />
          <input type="text" class="form-control" value="<?= $this->client->getName() ?>"
                 id="country_name" placeholder="País">
          <p class="help-block"><?= $this->client->getErrors('country') ?></p>
        </div>
      </div>

      <div class="form-group col-xs-12">

        <div class="form-group col-md-3 <?= $this->client->getErrors('phone') ? 'has-error' : '' ?>">
          <label class="control-label" for="phone">Telefone:*</label>
          <input type="text" class="form-control" name="client[phone]" value="<?= $this->client->getName() ?>"
                 id="phone" placeholder="Telefone">
          <p class="help-block"><?= $this->client->getErrors('phone') ?></p>
        </div>

        <div class="form-group col-md-4 <?= $this->client->getErrors('mobile') ? 'has-error' : '' ?>">
          <label class="control-label" for="mobile">Celular:*</label>
          <input type="text" class="form-control" name="client[mobile]" value="<?= $this->client->getName() ?>"
                 id="mobile" placeholder="Celular">
          <p class="help-block"><?= $this->client->getErrors('mobile') ?></p>
        </div>

        <div class="form-group col-md-4 <?= $this->client->getErrors('leave_message') ? 'has-error' : '' ?>">
          <label class="control-label" for="leave_message">Recado:*</label>
          <input type="text" class="form-control" name="client[leave_message]" value="<?= $this->client->getName() ?>"
                 id="leave_message" placeholder="Recado">
          <p class="help-block"><?= $this->client->getErrors('leave_message') ?></p>
        </div>

      </div>

      <div class="form-group col-xs-12">
        <button type="submit" class="btn btn-primary"> <?= $this->submit ?></button>
      </div>


    </form>

  </div>

</div>
