<div class="form-group col-xs-12">

  <div class="form-group col-md-3 <?= $this->client->getErrors('doc') ? 'has-error' : '' ?>">
    <label class="control-label" for="doc" id="label_doc" >CPF:*</label>
    <input type="text" class="form-control" name="client[doc]" value="<?= $this->client->getDoc() ?>"
           id="doc" placeholder="CPF">
    <p class="help-block"><?= $this->client->getErrors('doc') ?></p>
  </div>

  <div class="form-group col-md-4 <?= $this->client->getErrors('name') ? 'has-error' : '' ?>">
    <label class="control-label" for="name">Nome:*</label>
    <input type="text" class="form-control" name="client[name]" value="<?= $this->client->getName() ?>"
           id="name" placeholder="Nome" />
    <p class="help-block"><?= $this->client->getErrors('name') ?></p>
  </div>

  <div class="form-group col-md-4 <?= $this->client->getErrors('more_names') ? 'has-error' : '' ?>">
    <label class="control-label" for="more_names">Sobrenome:*</label>
    <input type="text" class="form-control" name="client[more_names]" value="<?= $this->client->getMoreNames() ?>"
           id="more_names" placeholder="Sobrenome">
    <p class="help-block"><?= $this->client->getErrors('more_names') ?></p>
  </div>

</div>
