<header class="page-header clearfix">
  <h1>Clientes</h1>
  <?= ViewHelpers::linkTo('/clientes/novo', 'Novo Cliente  <span class="glyphicon glyphicon-plus">', 'class="btn btn-primary pull-left"') ?>
</header>

<div>
    <h2>Todos</h2>
    <table class='table table-bordered table-striped sortable'>
        <thead>
            <tr>
                <th>ID</th>
                <th>CPF/CNPJ</th>
                <th>Nome/Nome Fantasia</th>
                <th>Tipo</th>
                <th class="sorttable_nosort"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->clients as $client) {?>
            <tr>
                <td><?= $client->getId() ?></td>
                <td><?= $client->maskDoc() ?></td>
                <td><?= $client->getName() ?> <?= $client->getMoreNames() ?></td>
                <td><?= Client::prettyType($client->getType()) ?></td>
                <td>
                  <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/editar", '<span class="glyphicon glyphicon-pencil" data-toggle="tooltip" title="Editar" ></span>', 'class="btn btn-xs btn-warning"' ) ?>
                  <?= ViewHelpers::linkTo("/clientes/{$client->getId()}", '<span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="Visualizar" ></span>', 'class="btn btn-xs btn-success" href="#details"' ) ?>
                  <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/deletar", '<span class="glyphicon glyphicon-trash" data-toggle="tooltip" title="Deletar" ></span>', 'class="btn btn-xs btn-danger"' ) ?>
                  <?= ViewHelpers::linkTo("/clientes/{$client->getId()}/pedidos/novo", '<span class="glyphicon glyphicon-plus" data-toggle="tooltip" title="Novo Pedido" ></span>', 'class="btn btn-xs btn-primary"' ) ?>
                </td>
            </tr>
            <?php } ?>
         </tbody>
     </table>
     <?= ViewHelpers::paginate($this); ?>
</div>
