<div class="col-xs-4 col-xs-offset-1 search-area">

  <div class="panel panel-default">

    <div class="panel-heading">Buscar pedidos</div>

    <div class="panel-body">

      <form action="<?= ViewHelpers::urlFor("/pedidos/busca/") ?>" method="POST">

        <div class=".col-lg-6">

          <div class="input-group">

            <input type="hidden" id="order_id" name="order_id" />

            <input type="text" class="form-control" data-url="<?= ViewHelpers::urlFor('/clientes/auto_complete_search') ?>" name="name" id="autocomplete_clients" placeholder="Cliente, Vendedor, ID do pedido..."/>

            <span class="input-group-btn">
              <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
            </span>

          </div><!-- /input-group -->

        </div><!-- /.col-lg-6 -->

      </form>

    </div><!-- /.panel-body -->

  </div><!-- /.panel panel-default -->

</div>
