<section>
  <header class='page-header'>
    <h1>Pedido nº <?= $this->order->getId() ?></h1>
    <h3>Cliente - <?= $this->order->getClient()->getName() ?></h3>
    <div class="clearfix">
      <?php if($this->order->getStatus() == 0) require "_search_bar.phtml"; ?>
    </div>

  </header>
  <div class="container-fluid">
    <h2 style="text-align: center">Pedido Vazio!</h2>
    <div class="col-xs-offset-4">
        <?= ViewHelpers::imageTag("/images/empty_order.jpg", "style='padding: 0 auto'") ?>
    </div>
  </div>
</section>
