<form role="form" action="<?= ViewHelpers::urlFor($this->action) ?>" method="POST">

  <div class="form-group <?= $this->product->getErrors('name') ? 'has-error' : '' ?>">
    <label class="control-label" for="product_name">Nome:*</label>
    <input type="text" class="form-control" name="product[name]" value="<?= $this->product->getName() ?>"
           id="product_name" placeholder="Produto">
    <p class="help-block"><?= $this->product->getErrors('name') ?></p>
  </div>

  <div class="form-group <?= $this->product->getErrors('category_id') ? 'has-error' : '' ?>">
    <label class="control-label" for="product_category_id">Categoria:*</label>
    <select class="form-control" name="product[category_id]" id="product_category_id">
      <option value="<?= $this->product->getCategory() ? $this->product->getCategory()->getId() : "" ?>"><?= $this->product->getCategoryId() ? $this->product->getCategory()->getName() : "Selecione uma categoria" ?></option>
      <?php foreach ($this->categories as $category) {?>
        <option value="<?= $category->getId() ?>"><?= $category->getName() ?></option>
      <?php } ?>
    </select>
    <p class="help-block"><?= $this->product->getErrors('category_id') ?></p>
  </div>

  <div class="form-group <?= $this->product->getErrors('price') ? 'has-error' : '' ?>">
    <label class="control-label" for="product_price">Preço:*</label>
    <input type="text" class="form-control" name="product[price]" value="<?= $this->product->getPrice() ?>"
           id="product_price" placeholder="R$">
    <p class="help-block"><?= $this->product->getErrors('price') ?></p>
  </div>

  <div class="form-group <?= $this->product->getErrors('stock') ? 'has-error' : '' ?>">
    <label class="control-label" for="product_price">Quantidade:*</label>
    <input type="text" class="form-control" name="product[stock]" value="<?= $this->product->getStock() ?>"
           id="product_stock" placeholder="R$">
    <p class="help-block"><?= $this->product->getErrors('stock') ?></p>
  </div>

  <button type="submit" class="btn btn-primary"> <?= $this->submit ?></button>
</form>
