<section>
  <header class='page-header'>
    <h1><?= $this->product->getName() ?></h1>
    <h3>Visualizando Produto</h3>
  </header>
  <div>

      <table class='table table-bordered table-striped sortable'>
          <thead>
              <tr>
                  <th>ID</th>
                  <th>Nome</th>
                  <th>Categoria</th>
                  <th>Quantidade em Estoque</th>
                  <th>Preço Unitário</th>
                  <th>Data de cadastro</th>
                  <th class="sorttable_nosort"></th>
              </tr>
          </thead>
          <tbody>
              <tr>
                  <td><?= $this->product->getId() ?></td>
                  <td><?= ViewHelpers::truncate($this->product->getName()) ?></td>
                  <td><?= $this->product->getCategory()->getName() ?></td>
                  <td><?= $this->product->getStock() ?></td>
                  <td><?= ViewHelpers::currencyFormat($this->product->getPrice()) ?></td>
                  <td><?= ViewHelpers::dateFormat($this->product->getCreatedAt()) ?></td>
                  <td>
                    <?= ViewHelpers::linkTo("/produtos/{$this->product->getId()}/editar", '<span class="glyphicon glyphicon-pencil" data-toggle="tooltip" title="Editar" ></span>', 'class="btn btn-xs btn-warning"' ) ?>
                    <?= ViewHelpers::linkTo("/produtos/{$this->product->getId()}/deletar", '<span class="glyphicon glyphicon-trash" data-toggle="tooltip" title="Deletar" ></span>', 'class="btn btn-xs btn-danger"' ) ?>
                  </td>
              </tr>
           </tbody>
       </table>

  </div>
</section>
