<header class="page-header clearfix">
  <h1>Relatórios</h1>
</header>

<input type="hidden" id="graphic-title" value="Produtos Mais Vendidos"/>
<input type="hidden" id="graphic-subtitle" value="Quantidade de vendas no período <?= $this->range ?>"/>
<input type="hidden" id="top-x" value="Top 5"/>

<div class="col-xs-8 col-xs-offset-2">
  <form class="form-inline "role="form" action="<?= $this->action ?>" method="POST">
    <div class="form-group">
      <label class="control-label" for="date[beginDate]">Data de Início</label>
      <input type="date" class="form-control" name="date[beginDate]" />
    </div>

    <div class="form-group">
      <label class="control-label" for="date[endDate]">Data de Fim</label>
      <input type="date" class="form-control" name="date[endDate]" />
    </div>

    <button type="submit" class="btn btn-primary btn-sm"><?= $this->submit ?></button>

  </form>
</div>

<div class="fluid-container">

  <div class="row">

    <div class="col-xs-8 col-xs-offset-1" id="chart" data-graphic='<?= $this->bestSellingProducts() ?>'></div>

  </div>

</div>
